name: Continuous Benchmarks
on: pull_request
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.read_touchstone_config.outputs.config }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - id: read_touchstone_config
        run: |
          content=`cat ./touchstone/config.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=config::$content"
  build:
    needs: prepare
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.config) }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BENCHMARKING_REPO: "lorenzwalthert/here"
      BENCHMARKING_REF: "ca9c8e69c727def88d8ba1c8b85b0e0bcea87b3f"
      BENCHMARKING_PATH: "touchstone/sources/here"
    steps:
      - name: Set up git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Ensure base branch is fetched
        run: |
          git checkout -b $GITHUB_HEAD_REF
          git branch $GITHUB_BASE_REF remotes/origin/$GITHUB_BASE_REF
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-3-
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          sudo apt-get install libcurl4-openssl-dev libgit2-dev
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('ggplot2', 'purrr'))" -e "remotes::install_deps(dependencies = TRUE); remotes::install_github(c('r-lib/bench', 'lorenzwalthert/touchstone')); "
          R CMD INSTALL .
      - name: Checkout benchmarking repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BENCHMARKING_REPO }}
          ref: ${{ env.BENCHMARKING_REF }}
          path: ${{ env.BENCHMARKING_PATH }}
      - name: Prepare PR comment
        run: |
          mkdir -p touchstone/sources
          mkdir -p touchstone/pr-comment
          mkdir -p touchstone/plots
          echo "Here is how the current PR would change benchmark results when merged into $GITHUB_BASE_REF:" > touchstone/pr-comment/info.txt
          echo "$GITHUB_EVENT_PULL_REQUEST_HEAD_SHA" >> touchstone/pr-comment/info.txt
      - name: Run benchmarks
        run: Rscript 'touchstone/script.R'
      - uses: actions/upload-artifact@v2
        with:
          name: visual-benchmarks
          path: touchstone/plots/
      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: touchstone/pr-comment
      - uses: actions/download-artifact@v1
        with:
          name: results
      - name: comment PR
        run: cat touchstone/pr-comment/info.txt
